### ISSUE TITLE
Data models loading in version 3.0.0

### ISSUE THREAD

**Issue by advancedlogic** [clir/clearnlp#1]
Hi,
I am trying to use the new version but it looks like I cannot load the dictionary model, the postagger model and the dependency model (In version 2 was sufficient to have the data models in the pom files and you did not have to specify any path). Could you provide me with a simple example with maven.
Apparently my  app is not able to find the path to the data model in the jars. I tried also to unpack the jar and use the gzip file but it does not work either.
Thanks

**Comment by jdchoi77** [comment]
Hi,

I'm on the process of uploading all these models.  I'll make an official announcement of this release in a couple of days so please sign up our Google discussion group so you'll get the notification.  Thank you!

best,

Jinho

**Comment by jdchoi77** [comment]
Antonio,

I put a new instruction on our guideline page, which uses the new release 3.0.1 (not 3.0.0).  Could you please check this again and let me know if you still have trouble?  Thank you.

https://github.com/clir/clearnlp-guidelines/blob/master/md/getting_started/models.md

best,

Jinho

**Comment by advancedlogic** [comment]
thanks,
I already did it this afternoon (Italy) and it works. Thanks
Very looking forward to testing SRL as well.

**Comment by jdchoi77** [comment]
Great, please sign up our google group so you can get the notification of the new release.

https://groups.google.com/forum/#!forum/clearnlp

best,

Jinho

http://mathcs.emory.edu/~choi/
Assistant professor, Emory University

On Mar 18, 2015, at 4:45 PM, Antonio Linari <notifications@github.com<mailto:notifications@github.com>> wrote:

thanks,
I already did it this afternoon (Italy) and it works. Thanks
Very looking forward to testing SRL as well.


Sent from my iPhone

> On Mar 18, 2015, at 9:39 PM, Jinho D. Choi <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Antonio,
>
> I put a new instruction on our guideline page, which uses the new release 3.0.1 (not 3.0.0). Could you please check this again and let me know if you still have trouble? Thank you.
>
> https://github.com/clir/clearnlp-guidelines/blob/master/md/getting_started/models.md
>
> best,
>
> Jinho
>
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub<https://github.com/clir/clearnlp/issues/1#issuecomment-83163813>.


________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
