### ISSUE TITLE
Tokenization

### ISSUE THREAD

**Issue by cbrew** [clir/clearnlp#9]
Good practice in tokenization is to make the tokenization pipeline information preserving, in the sense that you can always recover the original form of the input document, including details of whitespace and other formatting and encoding details. If you do that, you can anchor every annotation (morphs, words, pos-tags, dependencies, named entities and SRL) back to locations in the original input. You have to be a little indirect sometimes, because it is no longer OK to directly change the input data. You have to record the change, and keep the original, while presenting the right view to later stages in the pipeline.

The ClearNLP tokenizer (I believe) loses information about whitespace in tokenize.AbstractTokenizer.tokenizeWhitespace, and is fairly free in tinkering with the input. This would be good to fix. If there is interest, I'll try.

**Comment by hradba** [comment]
I would appreciate this!

**Comment by jdchoi77** [comment]
Chris,

This is a great idea.  I actually started a new project called Emory NLP, which will be ready by the end of this semester.  In this project, I separated the tokenizer from the core NLP so it makes contributions from others easier.

https://github.com/emorynlp/tokenizer

Would you be interested in contributing to our project?  I want this project to be really community-based and you know ClearNLP better than most others so please let me know if you do then I'll invite you to the project.  Thank you!

best,

Jinho

**Comment by cbrew** [comment]
Jinho,

yes, sure. I can't be completely sure how much time I will have, but this is something that I do want to contribute to.

Chris

**Comment by jdchoi77** [comment]
Chris,

I just invited you to the other project.  The Emory NLP project will be ready to be released by the end of this semester and after that, I may need more help from you :)

Jinho
